CC=gcc
LEX=lex
YACC=yacc

all: gpp_interpreter

gpp_interpreter: lex.yy.c y.tab.c
	$(CC) lex.yy.c y.tab.c -o gpp_interpreter
	
lex.yy.c: gpp_lexer.l
	$(LEX) gpp_lexer.l

y.tab.c: gpp_interpreter.y
	$(YACC) -d gpp_interpreter.y

clean:
	rm -f lex.yy.c y.tab.c gpp_interpreter
